server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



spring:
  application:
    name: service-feign
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
      base-url: http://119.23.43.137:9411/ # 指定了 Zipkin 服务器的地址







feign:
   hystrix:
      enabled: true
